### ISSUE TITLE
Movement Error

### ISSUE THREAD

**Issue by DamondSD** [trdischat/conditions5e#16]
I am unsure what exactly is happening. 

During a session two days ago, we were experiencing a massive lag issue. Checking the console I was shocked to see over 400 errors. 

It has taken me two days to narrow down and find the badly behaving mod, and it turns out to be conditions5e. 

Info: 

Platform: Windows 10
Browser: Chrome
Foundry Version: 0.7.9

Error: When selecting a token then moving said token, we receive  foundry.js:44970 Uncaught (in promise) TypeError:
https://prnt.sc/10m1b7y

All mods deactivated except for conditions5e

I have been able to repeat this error in four different game worlds. Strangely, it does not seem to affect all tokens. 
I have tried replacing the actors, recreating the actors, all to the same error.

**Comment by trdischat** [comment]
Thanks for the report.  Unfortunately, I retired this module a few months ago, since CUB has largely replaced it, and it appears that the methods that I used in this module are not very compatible with version 0.7.x of FVTT.  Getting it to work with the current version of Foundry would require a near complete rewrite, which I don't have time for right now.  Sorry.
